name: Build and Copy to 'build' Branch

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Require Node
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install and Build
        run: |
          mkdir build
          cd build
          touch index.html

      - name: Checkout to 'build' branch
        uses: actions/checkout@v4
        with:
          ref: build

      - name: Push './build' folder to branch
        run: |
          ls
          cd ./build
          git add .
          git commit -m "generated"
          git push
        
